name = "ComplexMultiplicationFields"
uuid = "7a21829d-fee9-480e-8b0f-ee2c98df13fb"
authors = ["Bogdan AAdrian Dina"]
version = "0.1.0"

[compat]
julia = "1.8"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
